blog/urls.py
from django.urls import path, include
# from django.contrib import admin
from . import views

app_name = 'blog'
urlpatterns = [
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    # path('<int:pk>/', views.single_post_page),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment, name='comment_delete'),
    # path('delete_comment/<int:pk>/', views.CommentDelete.as_view(), name='comment_delete'),


]
# class PostList(ListView):


# urlpatterns = [
#     path('<int:pk>', views.single_post_page),
#     path('', views.index),
# ]
# def index(request):
#     return render()
# def single_post_page(request, pk):
#     return render()

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('blog1/', include('blog1.urls')),
    path('tour/', include('tour.urls')),
    # path('', include('single_pages.urls')),
    path('blog/', include('blog.urls')),
    path('', include('single_pages.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('crm/', include('website.urls')),
    path('tinymce/', include('tinymce.urls')),
]

# static() 정적 파일들의 url을 관리. 접근한 url을 리턴.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdown



    # //FIXME: ForeignKey -> User의 pk와 연결돼 있다는 말
#django 라이브러리, db.models 모듈 임포트 후, Model클래스 상속
#Post/title,content,created_at
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True, allow_unicode=True)
    # category=None 카테고리 미분류, 태그 미분류는 없자낭

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'
        # return f'/blog/category/{self.slug}/'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, null=True, blank=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'
        # return f'/blog/category/{self.slug}/'
    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=80)
    hook_text = models.CharField(max_length=120, blank=True)
    # content = models.TextField()
    content = MarkdownxField()
    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #//FIXME: ForeignKey -> User의 pk와 연결돼 있다는 말
    author = models.ForeignKey(User,null=True, on_delete=models.SET_NULL)
    # 카테고리 삭제했다고, 연결된 Post까지 삭제되면 안됨 -> models.SET_NULL
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag,blank=True)

#  __str__메서드 : 객체 자체의 내용을 출력
    def __str__(self):
        return f'[{self.pk}] {self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'
    
    def get_file_name(self):
        return os.path.basename(self.file_upload.name)
    # basename(): 파일이름만
# split(파일) : 디렉토리와 파일 분리, splitext():확장자만, dirname: 디렉토리만 ,   isdir(): 디렉토리인지?
    def get_file_ext(self):

        return self.get_file_name().split('.')[-1]
        # return os.path.splitext(self.file_upload.name)

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    # Comment클래스는 Post보다 아래 있어야 한다!!
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} :: {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.text import slugify

from .forms import CommentForm
from .models import Category, Tag, Post, Comment


# 코멘트폼 필요. forms.py 에 모델폼 상속.
def new_comment(request, pk):
    # pk ? 폼 액션을 통해서 받겠지? post.get_absolute_url/new_comment/
    if request.user.is_authenticated:
        # 포린키 저장시. post객체 필요. Comment(post = post 객체, author= request.user),
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())

    else:
        raise PermissionDenied

# def update_comment(request,pk):
#     pass
    # template_name = Comment_form.html
    # UpdateView

    # ImproperlyConfigured at Using ModelFormMixin (base class of CommentUpdate) without the 'fields' attribute is prohibited.)
class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    # model 을 지정하면, 자동으로 해당 ModelForm을 상속한 CommentForm이 생성.form_class = CommentForm
    fields = ['content'] # form_class = CommentForm 로 커스텀 가능.
    # fields를 지정하면, form_class 를 생략할 수 있다.


    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post # redirect 위해, post 필요
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

# 클래스 만들 때, 모델명을 앞에 쓰는 것이 규칙! 템플릿 comment_list, _detail, form_class = CommentFomr()등
# class CommentDelete(DeleteView):
#     model = Comment
#     context_object_name = 'comment' #post, post_list
#
#     # fields
#     # template_name =
#     success_url = ('/blog/') # post pk 를 어케 받지? 인자받는 방법. reverse_lazy, args .. 등. 몰라.
#
#
#     def get(self, request, *args, **kwargs):
#         return self.post(request, *args, **kwargs)

# 함수형: {% for p in posts %} {% endfor %} {{p.get_absolute_url }}
# 클래스형: for p in object_list

# //FIXME: tag 와 카테고리 차이. 미분류가 없다. N:N 으로..
#  태그 전부 출력시. iterator, all 등 관계는 없는 듯.
def tag_page(request, slug):
    # path('tag/<str:slug>/', views.tag_page)
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all().order_by('-pk')

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'tags': Tag.objects.all(),
            'tag': tag,
        }
    )


def category_page(request, slug):
    # path('category/<str:slug>/', views.category_page)
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None).order_by('-pk')
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category).order_by('-pk')

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        }
    )
    # 미분류는 카테고리 값이 없어서, category.post_set.count 처럼 카테고리객체를 참조하는 포린키 post로 역참조 불가.
    # no_category_post_count: Post 객체로 정방향 조회. category=None


class CategoryList(ListView):
    # path('category2/<str:slug>/', views.CategoryList.as_view())
    model = Post
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        return Post.objects.order_by('-created_at')[:100]


class PostList(ListView):
    model = Post
    ordering = '-pk'
    template_name = 'blog/post_list.html'

    def get_context_data(self, **kwargs):
        # context = super(PostList, self).get_context_data()
        context = super().get_context_data()
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context


# PostList(ListView)에서 model = Post 만 하면,
# get_context_data()가 post_list = Post.objects.all() 을 했었던 것.
# super(PostList, self) PostList의 부모인 ListView를 자식클래스로 불러서, 딕셔너리형태로 기능 추가.

class PostDetail(DetailView):
    model = Post
    # ordering = '-pk'
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        # context = super(PostDetail, self).get_context_data()
        context = super().get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm

        if self.object.tags.exists():
            # tags_str_list = list()
            # for t in self.object.tags.all():
            #     tags_str_list.append(t.name)
            # context['tags'] = '; '.join(tags_str_list)
            context['tags'] = self.object.tags.all()
            # self.object 가 post_list는 object_list처럼, object인데, 왜 self?? 클래스변수면 생략가능., 메서드, 객체변수니까.

        return context
    # template_name = 'blog/single_post_page.html'
    # 함수형을 쓰더라도, 템플릿파일명은 클래스형을 가정하고 만들자.
    # template_name = 'blog/post_detail.html'


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()

                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    # 새로 만든 포스트(self.object)의 tags 필드에 tag추가
                    self.object.tags.add(tag)

            return response

        else:
                return redirect('/blog/')

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']

    template_name = 'blog/post_update_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = '; '.join(tags_str_list)

        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)

        return response


# def index(request):
#     # posts = Post.objects.all()
#     posts = Post.objects.all().order_by('-pk');
#
#     return render(
#         request,
#         'blog/index.html',
#         {
#             'posts': posts,
#         }
#         )

# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk)
#
#     return render(
#         request,
#         'blog/single_post_page.html',
#         {
#             'post': post,
#         }
#     )

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <title>{% block head_title %}블로그{% endblock %}</title>
    <!-- <link href="./bootstrap4/css/bootstrap.min.css" rel="stylesheet" type="text/css"> -->
    <link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <script src="https://kit.fontawesome.com/726bbd6862.js" crossorigin="anonymous"></script>
</head>

<body>
{% include 'blog/navbar.html' %}

    <!-- Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="logInModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel"> <i class="fas fa-sign-in-alt"></i>&nbsp Log In</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <button type="button" class="btn btn-outline-dark btn-block btn-sm "><i
                                    class="fab fa-google"></i>&nbsp&nbsp Log in with Google</button>
                            <button type="button" class="btn btn-outline-dark btn-block btn-sm "><i
                                    class="far fa-envelope"></i>&nbsp&nbsp Log in with E-mail</button>
                        </div>
                        <div class="col-md-6">
                            <button type="button" class="btn btn-outline-dark btn-block btn-sm"><i
                                    class="far fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail</button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

<!-- //TODO: -->
    <div class="container my-3">
        <div class="row">
            <div class="col-md-8 col-lg-9" id="main-area">
               
                {% block main_area%}
                {% endblock %}

            </div>

            <div class="col-md-4 col-lg-3">
                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Search</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>

                <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">카테고리</h5>
                    
                    <div class="card-body">
                        <div class="row">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#">category.post_set.역참조</a></li>
                                {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count}})</a></li>
                                {% endfor %}
                                <li><a href="/blog/category/no_category/">미분류 ({{no_category_post_count}})</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                                <!-- 태그 Widget //TODO:-->

                <div class="card my-4">
                    <h5 class="card-header">태그</h5>
                    
                    <div class="card-body">
                        <div class="row">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#"></a></li>
                                {% for tag in tags %}
                                <li><a href="{{ tag.get_absolute_url }}">{{ tag }} ({{ tag.post_set.count}})</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% include 'blog/footer.html' %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>

</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}


{% block main_area %}
    <div id="post-area">
        {% if post.category %}
            <span class="badge badge-secondary float-right">{{ post.category }}</span>
        {% else %}
            <span class="badge badge-secondary float-right">미분류</span>
        {% endif %}

        <!-- Title -->

        <h1 class="mt-4">{{ post.title }}</h1>
        <h5 class="text-muted">{{ post.hook_text }}</h5>
        <!-- Author -->
        <p class="lead">
            by
            <a href="#">{{ post.author | upper }}</a>
        </p>

        <hr>

        {% if user.is_authenticated and user == post.author or user.is_superuser %}
            <a class="btn btn-info btn-sm float-right" href="/blog/update_post/{{ post.pk }}/" role="button"><i class="fas fa-pen"></i>  Edit Post</a>
        {% endif %}

        <!-- Date/Time -->
        <p>Posted on {{ post.created_at }}</p>

        <hr>

        <!-- Preview Image -->
        {% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image">
        {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/800/200" alt="random_image">
        {% endif %}


        <hr>
<!-- Post content-->
<section class="mb-5">
    <p class="fs-5 mb-4">
        {{ post.get_content_markdown | safe }}
    </p>
    {% if post.file_upload %}
        <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>다운로드
        {% if post.get_file_ext == 'csv' %}
        <i class="fas fa-file-csv"></i>
        {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
        <i class="fas fa-file-excel"></i>
        {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
        <i class="fas fa-file-word"></i>
        {% else %}
        <i class="far fa-file"></i>
        {% endif %}
        </a>
        <a href="{{ post.file_upload.url }}" target="_blank">{{ post.get_file_name }}</a><br>post.file_upload: {{ post.file_upload }}
    {% endif %}
    <br>
    태그 : {{ tags }} <br>
    <i class="fas fa-tags"></i> 태그2 : {% if tags.exists %}
        {% for tag in tags %}
    <a href="{{ tag.get_absolute_url }}">{{ tag.name }} </a>
        {% endfor %}
    {% endif %}
    </section>
<hr>
</div>
<div id="comment-area">
        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ comment_form | crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                {% else %}
                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">Log in and leave a comment</a>
                {% endif %}
            </div>
        </div>
{% if post.comment_set.exists %}
            {% for comment in post.comment_set.iterator %}
                <!-- Single Comment -->
                <div class="media mb-4" id="comment-{{ comment.pk }}">
                    <img class="d-flex mr-3 rounded-circle" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}" width="60px">
                    <div class="media-body">
                        {% if user.is_authenticated and comment.author == user %}
                            <div class="float-right">
                                <a role="button"
                                   class="btn btn-sm btn-info"
                                   id="comment-{{ comment.pk }}-update-btn"
                                   href="/blog/update_comment/{{ comment.pk }}/">
                                    edit
                                </a>
                                <a role="button"
                                   href="#"
                                   id="comment-{{ comment.pk }}-delete-modal-btn"
                                   class="btn btn-sm btn-danger"
                                   data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">
                                    delete
                                </a>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">Are You Sure?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <del>{{ comment | linebreaks }}</del>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            <a role="button" class="btn btn-danger" href="/blog/delete_comment/{{ comment.pk }}/">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                        <h5 class="mt-0">
                            {{ comment.author.username }}
                            &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                        </h5>
                        <p>{{ comment.content | linebreaks }}</p>
                        {% if comment.created_at != comment.modified_at %}
                            <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    글쓰기post컨텍스트는? - 브라우저 header
{% endblock %}

{% block main_area %}
    <h1>새 글 쓰기</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <div id="div_id_tags_str">
            <label for="id_tags_str">Tags:</label>
            <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control">
        </div>
        <br />
<!--        <table>-->
<!--            {{form}}-->
<!--            <tr>-->
<!--                <th>-->
<!--                    <label for="id_tags">Tags:</label>-->
<!--                </th>-->
<!--                <td>-->
<!--                    <input type="text" name="tags" id="id_tags"></input>-->
<!--                </td>-->
<!--            </tr>-->
<!--        </table>-->
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block head_title %}
    {{ post_list.first }} - 브라우저 header
{% endblock %}
{% block main_area %}
    {% if user.is_authenticated%}
        {% if user.is_superuser or user.is_staff %}
            <a class="btn btn-info btn-sm float-right" href="/blog/create_post/" role="button"><i class="fas fa-pen"></i>&nbsp;&nbsp;새 글쓰기</a>
        {% endif %}
    {% endif %}

<!-- //TODO: category 가 있으면? view에서 보내는 context에 category가 있으면..즉,views.category_page 로 들어온거면...  -->
<!-- //FIXME: if category 는 category 객체가 있으면(즉, category_page뷰에서 넘어왔으면..  -->
<!-- //TODO : post_detail.html에서는 if post.category 즉, post.category 값이 있으면 출력, 없으면 '미분류' -->
    <h1>전체 상품
        {% if category %}
         <span class="badge badge-secondary">카테고리: {{ category }}</span> 
        {% endif %}
        {% if tag %}
         <span class="badge badge-light"><i class="fas fa-tags"></i>태그: {{ tag }}({{ tag.post_set.count }})</span> 
        {% endif %}
    </h1>
<p>나는 post_list.html 이얌</p>
    {% for p in post_list %}
    <!-- Blog Post -->
    <div class="card mb-4">

        {% if p.head_image %}
        <img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head_image">
        {% else %}
        <img class="card-img-top" src="https://picsum.photos/seed/{{ p.id }}/400/400" alt="random_image">
        {% endif %}

        <div class="card-body">
            <h2 class="card-title"><a href="{{ p.get_absolute_url }}">{{p.title}}</a></h2>
            {% if p.hook_text %}
            <h4 class="text-muted">{{ p.hook_text }}</h4>
            {% endif %}
          
            <p class="card-text">
                {{ p.get_content_markdown |truncatewords_html:45 | safe }}
            </p>
      
            <p>
            <i class="fas fa-tags"></i>태그: 
            {% if p.tags.exists %}
                {% for tag in p.tags.iterator %}
                    {{ tag }} 이따레이터
                {% endfor %} 
            {% endif %}
                <br><br>
            <a href="{{ p.get_absolute_url }}" class="btn btn-primary">Read More (&rarr세미)&rarr;</a>
            </p>
        </div>
        <div class="card-footer text-muted">
            Posted on {{p.created_at}} by {{ p.author|upper }}
        </div>
    </div>
    {% endfor %}
    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
        </li>
    </ul>
{% endblock %}